/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * 
 */
public class Sugerencia extends javax.swing.JFrame {

    /**
     * Creates new form Sugerencia
     */
    public Sugerencia() {
        initComponents();

        this.setTitle("Sugerencia");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrinc = new javax.swing.JPanel();
        pnlDesc = new javax.swing.JPanel();
        txtToken = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPDesc = new javax.swing.JTextPane();
        pnlGram = new javax.swing.JPanel();
        txtToken1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPGram = new javax.swing.JTextPane();
        txtToken2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        pnlPrinc.setBackground(new java.awt.Color(51, 204, 255));
        pnlPrinc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDesc.setBackground(new java.awt.Color(51, 204, 255));

        txtToken.setEditable(false);
        txtToken.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtToken.setText("   DESCRIPCIÓN");
        txtToken.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtPDesc.setEditable(false);
        txtPDesc.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jScrollPane1.setViewportView(txtPDesc);

        javax.swing.GroupLayout pnlDescLayout = new javax.swing.GroupLayout(pnlDesc);
        pnlDesc.setLayout(pnlDescLayout);
        pnlDescLayout.setHorizontalGroup(
            pnlDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtToken, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlDescLayout.setVerticalGroup(
            pnlDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtToken, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(pnlDescLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlPrinc.add(pnlDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pnlGram.setBackground(new java.awt.Color(51, 204, 255));

        txtToken1.setEditable(false);
        txtToken1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtToken1.setText("   PRODUCCIONES");
        txtToken1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtPProd.setEditable(false);
        txtPProd.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jScrollPane2.setViewportView(txtPProd);

        txtPGram.setEditable(false);
        txtPGram.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jScrollPane3.setViewportView(txtPGram);

        txtToken2.setEditable(false);
        txtToken2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtToken2.setText("   GRAMÁTICA");
        txtToken2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnlGramLayout = new javax.swing.GroupLayout(pnlGram);
        pnlGram.setLayout(pnlGramLayout);
        pnlGramLayout.setHorizontalGroup(
            pnlGramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtToken2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(txtToken1, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlGramLayout.setVerticalGroup(
            pnlGramLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGramLayout.createSequentialGroup()
                .addComponent(txtToken2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(txtToken1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlPrinc.add(pnlGram, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, 430, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrinc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrinc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sugerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sugerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sugerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sugerencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sugerencia().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnlDesc;
    private javax.swing.JPanel pnlGram;
    private javax.swing.JPanel pnlPrinc;
    protected javax.swing.JTextPane txtPDesc;
    protected javax.swing.JTextPane txtPGram;
    protected static final javax.swing.JTextPane txtPProd = new javax.swing.JTextPane();
    private javax.swing.JTextField txtToken;
    private javax.swing.JTextField txtToken1;
    private javax.swing.JTextField txtToken2;
    // End of variables declaration//GEN-END:variables
}
